version: "3.9"

services:
  redis:
    container_name: redis
    image: redis
    restart: always
    ports:
    - "6379:6379"
    command:  redis-server --save 60 1 --loglevel warning
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_BEAT_MAX_LOOP_INTERVAL=600 # 10 دقیقه

  backend:
    build: .
    container_name: Cbv
    command:  gunicorn core.wsgi --bind 0.0.0.0:8000 
    volumes:
      - ./:/app
      - static_volume:/app/static
      - media_volume:/app/media
    expose:
      - "8000"
    environment:
      # SECRET_KEY: django-insecure-rh)10532-c8@@tz)gu$1*f*ff%1%3(&xvs#h8xqy$neo2q)4n0
      # DEBUG: "True"
      - SECRET_KEY=test
      - DEBUG=False
      - ALLOWED_HOSTS=* 
    depends_on:
      - redis

  redis-worker:
    build: .
    command: celery -A core worker --loglevel=info
    # command: celery -A core worker --loglevel=info --pool=redis

    volumes:
      - ./:/app
    depends_on:
      - redis
      - backend
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/1  

  master:
    image: locustio/locust
    ports:
     - "8089:8089"
    volumes:
      - ./locust:/mnt/locust
    command: -f /mnt/locust/locustfile.py --master -H http://backend:8000
  
  locust-worker:
    image: locustio/locust
    volumes:
      - ./locust:/mnt/locust
    command: -f /mnt/locust/locustfile.py --worker --master-host master
  nginx:

    image: nginx
    container_name: nginx
    restart: always
    ports: 
      - "80:80"
    depends_on:
      - redis
      - backend  
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/home/app/static
      - media_volume:/home/app/media
      
volumes:
  static_volume:
  media_volume:     