name: Django project

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Tests Outpot
      run : true
    # - name: Setup Docker-Compose
    #   run: docker-compose up -d
    # - name: Run tests
      # run: docker exec backend sh -c "black ."
