name: Django project

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Create .env file
      run: |
        echo "DJANGO_SECRET_KEY=django-insecure-rh)10532-c8@@tz)gu$1*f*ff%1%3(&xvs#h8xqy$neo2q)4n0" > .env
        echo "DEBUG=True" >> .env

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Set up Docker Compose
      run: |
        sudo apt-get update
        sudo apt-get install -y docker-compose

    - name: Start Docker Compose Services
      run: docker-compose up -d

    - name: Run Tests
      run: docker exec backend flake8
